# https://render.com/docs/preview-environments#environment-variables
services:
# A static site
- type: web
  name: static-test-site
  env: static
  staticPublishPath: ./
- type: cron
  name: cron-test
  env: python
  region: oregon
  schedule: "0 5 * * *"
  startCommand: "bash ./hello.sh"
