services:
# A static site
- type: web
  name: static-test-site
  env: static
  staticPublishPath: ./
  envVars:
  - fromGroup: project-settings
  - key: MY_KEY
    value: "my_value"

envVarGroups:
- name: project-settings
  envVars:
  - key: MY_OTHER_KEY
    value: "my_other_value"
