services:
# A static site
- type: web
  name: static-test-site
  env: static
  buildCommand: "#"
  staticPublishPath: ./

envVarGroups:
- name: stripe
  envVars:
  - key: STRIPE_API_URL
    value: https://api.stripe.com/v2
  - key: MY_SECRET
    value: "mysecretvalue"
  - key: MY_OTHER SECRET
    value: "mysecretvalue"
