services:
- type: web
  name: static-test-site
  env: static
  buildCommand: "#"
  staticPublishPath: ./
# A Ruby web service
- type: web
  name: another-ruby-test-site
  env: ruby
  repo: https://github.com/render-examples/sidekiq
  buildCommand: bundle install
  startCommand: bundle exec ruby main.rb
  envVars:
    # This environment variable is not valid, since a database named `giraffe` is not included in this render.yaml file
    - key: DB_URL_2
      fromDatabase:
        name: giraffe
        property: connectionString
  autoDeploy: false # optional
- type: web
  name: ruby-test-site
  env: ruby
  repo: https://github.com/render-examples/sidekiq
  buildCommand: bundle install
  startCommand: bundle exec ruby main.rb
  domains:
    - test0.render.com
    - test1.render.com
  envVars:
    - key: STRIPE_API_KEY
      value: Z2V0IG91dHRhIGhlcmUhCg
    # This environment variable is not valid, since a database named `zebra` is not included in this render.yaml file
    - key: DB_URL_2
      fromDatabase:
        name: zebra
        property: connectionString

envVarGroups:
- name: stripe
  envVars:
  - key: STRIPE_API_URL
    value: https://api.stripe.com/v2
  - key: MY_SECRET
    value: "mysecretvalue"
